# Generated by Django 4.2.11 on 2025-03-14 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'FAN',
                'verbose_name_plural': 'FANLAR',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('tel_num', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.fanlar')),
            ],
            options={
                'verbose_name': 'STUDENT',
                'verbose_name_plural': 'STUDENTS',
            },
        ),
    ]
